# Generated by Django 4.1 on 2022-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_itemtype_remove_removal_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
