# Generated by Django 4.1 on 2022-09-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='removal',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('ks', 'ks'), ('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], default='ks', max_length=256),
        ),
    ]
