# Generated by Django 4.1 on 2022-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_removal_item_type_remove_storage_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default='ks', max_length=256),
        ),
    ]
