# Generated by Django 4.1 on 2022-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_itempart_alter_product_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='discount',
            new_name='difference_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_increase',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
    ]
