# Generated by Django 4.1 on 2022-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_sold_alter_product_stocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
