# Generated by Django 4.1 on 2022-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_sum_transaction_sum_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='brand',
            field=models.BooleanField(default=True),
        ),
    ]
