# Generated by Django 4.1 on 2022-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transaction_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
