# Generated by Django 4.1 on 2022-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='city',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sale',
            name='country',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sale',
            name='ic_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='link',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='postal_code',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='route',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sale',
            name='street_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post_images'),
        ),
    ]
