# Generated by Django 4.1 on 2023-01-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sale_city_sale_country_sale_ic_number_sale_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='ic_number',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sale',
            name='postal_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sale',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
